<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-21T13:55:39+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      paths
 * @group     https
 * @namespace ssl_redirect_conf
 * -----------------------------------------------------------------------------
 */
return [
    'signin' => '1',
    'paths' => [
        '/login',
        '/login/*',
        '/dashboard',
        '/dashboard/*',
        '/contact',
        '/contact/*',
    ],
];
