<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-21T11:56:28+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Tokyo',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
