<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-12-31T13:25:52+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Tokyo',
    'theme_paths' => [
        '/account' => 'atomik',
        '/members/profile' => [
            'atomik',
            'profile.php',
        ],
    ],
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
