<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-09-17T10:44:07+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.clear.thumbnails
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1521600988,
        'do_page_reindex_check' => false,
        'latest_version' => '8.5.5',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'accessibility' => [
        'toolbar_titles' => false,
        'toolbar_tooltips' => false,
        'toolbar_large_font' => false,
        'display_help_system' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'maintenance' => [
        'version_job_page_num' => 220,
    ],
    'api' => [
        'enabled' => true,
        'grant_types' => [
            'client_credentials' => false,
            'authorization_code' => false,
            'password_credentials' => false,
            'refresh_token' => true,
        ],
    ],
];
