<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2022-03-23T11:11:32+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.tracking.code.footer
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'take make factory',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
                'tracking' => [
                    'code' => [
                        'header' => '<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-5931865-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag(\'js\', new Date());

  gtag(\'config\', \'UA-5931865-1\');
</script>
',
                        'footer' => '',
                    ],
                ],
            ],
        ],
    ],
];
