<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-03-15T20:41:25+09:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      connections.concrete
 * @group     database
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'default-connection' => 'concrete',
    'connections' => [
        'concrete' => [
            'driver' => 'c5_pdo_mysql',
            'server' => 'localhost',
            'database' => 'c5',
            'username' => 'c5',
            'password' => 'asdf1242',
            'character_set' => 'utf8',
            'collation' => 'utf8',
        ],
    ],
];
